id: A4B5E85B9
title: Invocation of the VidyÄdhara Gurus
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:09:15.219589
  last_modified_at: 2022-03-01 01:09:15.219603
